export const colleges = [
  // Maharashtra
  { name: 'Indian Institute of Technology Bombay (IITB)', short: 'IIT Bombay' },
  { name: 'College of Engineering, Pune (COEP)', short: 'COEP' },
  { name: 'Veermata Jijabai Technological Institute (VJTI)', short: 'VJTI Mumbai' },
  { name: 'Sardar Patel Institute of Technology (SPIT)', short: 'SPIT Mumbai' },
  { name: 'Dwarkadas J. Sanghvi College of Engineering (DJSCE)', short: 'DJSCE Mumbai' },
  { name: 'Vishwakarma Institute of Technology (VIT)', short: 'VIT Pune' },
  { name: 'MIT World Peace University (MIT-WPU)', short: 'MIT Pune' },
  { name: 'Symbiosis Institute of Technology (SIT)', short: 'SIT Pune' },
  { name: 'Ramrao Adik Institute of Technology (RAIT)', short: 'RAIT Navi Mumbai' },
  { name: 'Thadomal Shahani Engineering College (TSEC)', short: 'TSEC Mumbai' },
  { name: 'K. J. Somaiya College of Engineering (KJSCE)', short: 'KJSCE Mumbai' },
  { name: 'Government College of Engineering, Amravati (GCOEA)', short: 'GCOE Amravati' },
  { name: 'Government College of Engineering, Aurangabad (GCOEA)', short: 'GCOE Aurangabad' },
  { name: 'Government College of Engineering, Karad (GCEK)', short: 'GCOE Karad' },
  { name: 'Walchand College of Engineering, Sangli (WCE)', short: 'WCE Sangli' },
  { name: 'Visvesvaraya National Institute of Technology (VNIT)', short: 'VNIT Nagpur' },
  { name: 'Savitribai Phule Pune University (SPPU)', short: 'Pune University' },
  { name: 'Mumbai University (MU)', short: 'Mumbai University' },
  
  // Other Major Indian Colleges
  { name: 'Indian Institute of Technology Delhi (IITD)', short: 'IIT Delhi' },
  { name: 'Indian Institute of Technology Madras (IITM)', short: 'IIT Madras' },
  { name: 'Indian Institute of Technology Kanpur (IITK)', short: 'IIT Kanpur' },
  { name: 'Indian Institute of Technology Kharagpur (IIT-KGP)', short: 'IIT Kharagpur' },
  { name: 'Indian Institute of Science (IISc)', short: 'IISc Bangalore' },
  { name: 'National Institute of Technology Tiruchirappalli (NITT)', short: 'NIT Trichy' },
  { name: 'National Institute of Technology Karnataka (NITK)', short: 'NIT Surathkal' },
  { name: 'Vellore Institute of Technology (VIT)', short: 'VIT Vellore' },
  { name: 'Birla Institute of Technology and Science (BITS)', short: 'BITS Pilani' },
  { name: 'Delhi Technological University (DTU)', short: 'DTU' },
  { name: 'Netaji Subhas University of Technology (NSUT)', short: 'NSUT Delhi' },
  { name: 'Jadavpur University', short: 'Jadavpur University' },
  { name: 'Anna University', short: 'Anna University' },
  { name: 'Indian Institute of Technology Hyderabad (IITH)', short: 'IIT Hyderabad' },
  { name: 'Indian Institute of Technology (BHU) Varanasi', short: 'IIT BHU' },
  { name: 'All', short: 'All' },
];
